### ISSUE TITLE
Use Server Timing instead of X-Response-Time

### ISSUE THREAD

**Issue by Chi-teck** [middlewares/response-time#2]
[Server timing](https://w3c.github.io/server-timing/) is a standardized way to dispaly server side metrics.
Actually the PSR-15 implementation for Server Timing aready [exists](https://github.com/tuupola/server-timing-middleware) but it a bit compicated when compared with this package.

**Comment by oscarotero** [comment]
That's interesting but is a bit different of the purpose of this middleware, that only returns the time required to generate the response. The Server timing standard allows to create more granular data. Implementing this feature requires much more effort (and I'd create a new package instead reuse this one).

If you're interested in develop it, I can help you, but sadly I don't have enough time to implement it by myself.

**Comment by Chi-teck** [comment]
Response time is just one of the server side metrics. I don't think it is possible to create a generic middleware that would provide a complete set of application metrics because it depends on the architecture of the application. You'll need to mesure execution time of many different parts of the application. For instance Symfony components provide special traceable decorators for some services that collect metrics for profiler.
This issue is just about renaming `X-Response-Time`.

**Comment by oscarotero** [comment]
Ok, I guess we can add an option to change the name of the header.
Do you want to work on this? It's easy, jut need to create a function like this:
```php
$middleware = (new ResponseTime())->header('Server-Timing');
```

**Comment by Chi-teck** [comment]
Well, Server Timing has a special format.
`$response->withHeader('Server-Timing', 'total;desc="Request execution time";dur=' . $duration);`

**Comment by oscarotero** [comment]
Ok, so maybe a boolean option is more accurate:

```php
$middleware = (new ResponseTime())->serverTiming(true);
```

**Comment by Chi-teck** [comment]
I would pass the option through constructor. However, given the middlwere contains just a few lines of code, supporting two different formats would make it unnecessarily complex.  I think it's better to create a separate middleware for Server Timing.

**Comment by oscarotero** [comment]
Yeah, I think the same.
The existing PSR-15 implementation uses [Symfony Stopwatch](https://github.com/symfony/stopwatch) to collect the values. I think something like that could be simple to implement:

```php
use Symfony\Component\Stopwatch\Stopwatch;
use Middlewares\ServerTiming;

$stopwatch = new Stopwatch();
$middleware = new ServerTiming($stopwatch);
```

And that's all. The middleware only generates the header with all values collected by stopwatch, adding a new value with the response time.

But unfortunally, I don't have time to develop that. If you're interested, feel free to work on it.

**Comment by Chi-teck** [comment]
Installing Stopwatch to replace just one `microtime` seems to much. I've just published [Server Timing Middleware](https://github.com/Chi-teck/server-timing-middleware). Feel free to take it into this project if you wish. Thank you.
